### ISSUE TITLE
run error for object-detector-python with artpec8 camera

### ISSUE THREAD

**Issue by haichaoji123** [AxisCommunications/acap-computer-vision-sdk-examples#118]
### Environment

- Axis device model: [e.g. P3265-LVE ]
- Axis device firmware version: [e.g. 10.12.114]

tit works for Q1615 mkiii, but when compile with aarch64 for arpec8， it has error, here is the error

user@ubuntu:~/Downloads/acap-computer-vision-sdk-examples-main/object-detector-python$ docker-compose  --host tcp://192.168.1.234:2375 --env-file ./config/env.aarch64.artpec8 up
Starting object-detector-python_object-detector-python_1 ... done
Recreating object-detector-python_inference-server_1     ... done
Starting object-detector-python_acap_dl-models_1         ... done
Attaching to object-detector-python_object-detector-python_1, object-detector-python_acap_dl-models_1, object-detector-python_inference-server_1
acap_dl-models_1          | COPYRIGHT
acap_dl-models_1          | coco_labels.txt
acap_dl-models_1          | ssd_mobilenet_v2_coco_quant_postprocess.tflite
acap_dl-models_1          | ssd_mobilenet_v2_coco_quant_postprocess_edgetpu.tflite
object-detector-python_acap_dl-models_1 exited with code 0
object-detector-python_1  | object-detector-python connect to: unix:///tmp/acap-runtime.sock
object-detector-python_1  | Failed to initialize vdo stream
object-detector-python_1  | Traceback (most recent call last):
object-detector-python_1  |   File "detector.py", line 136, in <module>
object-detector-python_1  |     Detector().run()
object-detector-python_1  |   File "detector.py", line 103, in run
object-detector-python_1  |     self.run_camera_source()
object-detector-python_1  |   File "detector.py", line 114, in run_camera_source
object-detector-python_1  |     succeed, bounding_boxes, obj_classes, _ = self.detect(frame)
object-detector-python_1  |   File "detector.py", line 39, in detect
object-detector-python_1  |     image = image.astype(np.uint8)
object-detector-python_1  | TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
object-detector-python_object-detector-python_1 exited with code 1

**Comment by haichaoji123** [comment]
Hi, after upgrade firmware to 11.1. 55, it works. so it seems to be OS and SDK version issue.
